[package]
name = "bit_bool"
version = "0.1.0"
authors = ["LonnonjamesD <Limón#7879>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
